name: Docker CI

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

jobs:
  build-and-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker-compose build

      - name: Start containers
        run: docker-compose up -d

      - name: Show running containers
        run: docker ps -a

      - name: Show container logs (optionnel)
        run: docker-compose logs
